query Artist($slug: String!) {
  artists(filters: { slug: { eq: $slug } }) {
    data {
      id
      attributes {
        artistName
        slug
        description
        socialMedia {
          instagram
          soundcloud
          mixcloud
        }
        image {
          data {
            attributes {
              url
              formats
            }
          }
        }
        music_styles {
          data {
            attributes {
              style
            }
          }
        }
        radio_shows {
          data {
            attributes {
              longTitle
              slug
            }
          }
        }
      }
    }
  }
}
