query Artists {
  artists {
    data {
      attributes {
        artistName
        slug
        image {
          data {
            attributes {
              url
              formats
            }
          }
        }
        socialMedia {
          instagram
          soundcloud
          mixcloud
        }
        music_styles {
          data {
            attributes {
              style
            }
          }
        }
      }
    }
  }
}
