query LatestRadioShows {
  radioShows(sort: "updatedAt:desc", pagination: { limit: 5 }) {
    data {
      attributes {
        longTitle
        slug
        childShow {
          id
          date
          title
          description
          mixcloudUrl
          music_styles {
            data {
              attributes {
                style
              }
            }
          }
        }
      }
    }
  }
}
