query radioShows {
	radioShows(sort:"updatedAt:desc") {
    data {
      attributes {
        shortTitle
        slug
        image {
          data {
            attributes {
              name
              url
            }
          }
        }
        music_styles {
          data {
            attributes {
              style
            }
          }
        }
      }
    }
  }
}