query RadioShow($slug: String!) {
  radioShows(filters: { slug: { eq: $slug } }) {
    data {
      attributes {
        longTitle
        description
        slug
        artists {
          data {
            attributes {
              artistName
              slug
            }
          }
        }
        childShow {
          id
          date
          title
          description
          mixcloudUrl
          music_styles {
            data {
              attributes {
                style
              }
            }
          }
        }
      }
    }
  }
}
