query sisterRadios {
  sisterRadios {
    data {
      id
      attributes {
        title
        description
        link
        image {
          data {
            attributes {
              url
              formats
            }
          }
        }
      }
    }
  }
}
